# Generated by Django 6.1.1 on 2026-09-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
