# Generated by Django 6.1.1 on 2026-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, default='11-50 employees', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.IntegerField(blank=True, default=2020, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
